Implement gRPC program streaming service
rpcpool/yellowstone-vixen pull request #18
Opened 2024-08-24 04:47 UTC by ray-kast

Commits:
- **Retool metrics, reinstate OTel, bump dependencies.**
- **Add example crate for basic OpenTelemetry metrics.**
- **WIP: Implement gRPC streams + refactor everything.**

Remaining tasks:
- [ ] Test new push-based metrics with Prometheus gateway
- [ ] Test updated runtime code with multiple parsers
- [ ] Update all documentation to reflect API changes
- [ ] Solicit feedback on gRPC implementation
- [ ] Resolve remaining TODOs

2024-08-27 03:50 UTC, Nagaprasadvr reviewed
overall looks clean good to go

2024-08-27 03:50 UTC, Nagaprasadvr commented on crates/core/src/lib.rs
> +impl FromStr for Pubkey {
helpful

2024-08-27 03:50 UTC, Nagaprasadvr commented on crates/runtime/src/buffer.rs
> +impl<M: Instrumenter> Clone for Handler<M> {
good refactoring , i like the pipelines  idea

2024-08-27 03:50 UTC, Nagaprasadvr commented on examples/stream/src/main.rs
> +    vixen::stream::Server::builder()
looks clean

2024-08-30 05:34 UTC, Nagaprasadvr requested changes

2024-08-30 05:34 UTC, Nagaprasadvr commented on crates/core/src/instruction.rs
> +            return Err(Missing::InnerInstructions.into());
Every Outer ixs may not have inner ixs, i guess we should just ignore here and return an empty vector wyt @kespinola

2024-08-30 05:34 UTC, Nagaprasadvr commented on crates/core/src/instruction.rs
> +    pub shared: Arc<InstructionShared>,
for parsers we only need program , accounts , data 
 are we using this InstructionShared data somewhere else?

2024-08-30 05:34 UTC, Nagaprasadvr commented on crates/core/src/instruction.rs
> +    pub shared: Arc<InstructionShared>,
we can have AccountsShared instead of InstructionShared ig , and pass accounts as a vec of indices wyt?

2024-08-30 15:52 UTC, ray-kast commented on crates/core/src/instruction.rs
> +    pub shared: Arc<InstructionShared>,
`InstructionShared` is there to allow for more complex use cases that might need to e.g. store the slot or signature in which an instruction occurred in a database.

2024-08-30 15:58 UTC, ray-kast commented on crates/core/src/instruction.rs
> +            return Err(Missing::InnerInstructions.into());
That's my bad, I thought that was an implementation detail of the Protobuf encoding from yellowstone but it looks like it's an oddity with `solana-transaction-status`.  I will just ignore that field.

2024-08-30 16:06 UTC, Nagaprasadvr commented on crates/core/src/instruction.rs
> +    pub shared: Arc<InstructionShared>,
Makes sense then!

2024-08-30 16:06 UTC, Nagaprasadvr commented on crates/core/src/instruction.rs
> +            return Err(Missing::InnerInstructions.into());
cool

2024-09-02 10:16 UTC, Nagaprasadvr requested changes
Can we update the READMEs considering current architectural changes

2024-09-03 08:19 UTC, Nagaprasadvr requested changes
for Prometheus metrics to work ig we need to spin up a server at 0.0.0.0:3030 so metrics are pushed which can be consumed by the prometheus backed

or else we can also spin up a webserver using docker and expose port 3030 for use,
wyt @ray-kast  @kespinola 

check
https://github.com/rpcpool/yellowstone-vixen/blob/main/crates/runtime/src/buffer.rs#L62

2024-09-05 11:58 UTC, merged